/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "phone_book.h"
#include "util.h"

void
phone_book_prog_1( char* host, char* command )
{
	CLIENT *clnt;
	r_val  *result_1;
	entry  add_to_database_1_arg;
	r_val  *result_2;
	char * remove_from_database_1_arg;
	r_val  *result_3;
	char * lookup_name_1_arg;
	r_val  *result_4;
	char*  list_1_arg;
	int  *result_5;
	char*  quit_1_arg;
	int  *result_6;
	char*  terminate_1_arg;
	clnt = clnt_create(host, PHONE_BOOK_PROG, PHONE_BOOK_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	if(strcmp(command, "add")) {
		add_to_database_1_arg.name = malloc(sizeof(char) * 32);
		strcpy(add_to_database_1_arg.name, "David");

		add_to_database_1_arg.number = malloc(sizeof(char) * 32);
		strcpy(add_to_database_1_arg.name, "12345");

		add_to_database_1_arg.next = NULL;

		result_1 = add_to_database_1(&add_to_database_1_arg, clnt);
		if (result_1 == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		else {
			printf("result = %s\n", result_1->r_list->head->name);
		}
	}
	else if(strcmp(command, "delete")) {
		result_2 = remove_from_database_1(&remove_from_database_1_arg, clnt);
		if (result_2 == NULL) {
			clnt_perror(clnt, "call failed:");
		}
	}
	else if(strcmp(command, "query")) {
		result_3 = lookup_name_1(&lookup_name_1_arg, clnt);
		if (result_3 == NULL) {
			clnt_perror(clnt, "call failed:");
		}
	}
	else if(strcmp(command, "list")) {
		result_4 = list_1((void*)&list_1_arg, clnt);
		if (result_4 == NULL) {
			clnt_perror(clnt, "call failed:");
		}
	}
	else if(strcmp(command, "quit")) {
		result_5 = quit_1((void*)&quit_1_arg, clnt);
		if (result_5 == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		else {
			clnt_destroy( clnt );
		}
	}
	else if(strcmp(command, "terminate")) {
		result_6 = terminate_1((void*)&terminate_1_arg, clnt);
		if (result_6 == NULL) {
			clnt_perror(clnt, "call failed:");
		}
		else {
			clnt_destroy( clnt );
		}
	}
	else {
		printf("Invalid Command");
	}
}


int main( int argc, char* argv[] )
{
	char *host;
	char *command;
	int quit_program = 0;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];

	puts("Enter a command to use the phone book : ");

	while(1) {
		printf("\n> ");

		command = getLine();

		phone_book_prog_1( host, command );
	}

	return 0;
}

















