/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>

#include "phone_book.h"
#include "server_util.h"

r_val *
add_to_database_1_svc(entry *argp, struct svc_req *rqstp)
{
	static r_val  result;
	char phone_book_entry[256];

	printf("args %s, %s\n", argp->name, argp->number);
	FILE *fp = fopen("./database.txt", "a");

	strcpy(phone_book_entry, argp->name);
	strcat(phone_book_entry, "# ");
	strcat(phone_book_entry, argp->number);
	strcat(phone_book_entry, "\n");

	printf("entry : %s\n", phone_book_entry);

	if(fputs(phone_book_entry, fp) < 0) {
		perror("Error writing to file");

		result.num = -1;
		result.message = NULL;
	}
	else {
		result.num = ++COUNT;
		result.message = malloc(sizeof(char) * 64);
		strcpy(result.message, "Working");
	}

	fclose(fp);
	return(&result);
}

r_val *
remove_from_database_1_svc(char **argp, struct svc_req *rqstp)
{

	static r_val  result;

	

	return(&result);
}

r_val *
lookup_name_1_svc(char **argp, struct svc_req *rqstp)
{

	static r_val  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

r_val *
list_1_svc(void *argp, struct svc_req *rqstp)
{

	static r_val  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
quit_1_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
terminate_1_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
