/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PHONE_BOOK_H_RPCGEN
#define _PHONE_BOOK_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct entry {
	char *name;
	char *number;
	struct entry *next;
};
typedef struct entry entry;
#ifdef __cplusplus
extern "C" bool_t xdr_entry(XDR *, entry*);
#elif __STDC__
extern  bool_t xdr_entry(XDR *, entry*);
#else /* Old Style C */
bool_t xdr_entry();
#endif /* Old Style C */


struct linked_list {
	struct entry *head;
};
typedef struct linked_list linked_list;
#ifdef __cplusplus
extern "C" bool_t xdr_linked_list(XDR *, linked_list*);
#elif __STDC__
extern  bool_t xdr_linked_list(XDR *, linked_list*);
#else /* Old Style C */
bool_t xdr_linked_list();
#endif /* Old Style C */


struct r_val {
	int r_num;
	linked_list *r_list;
	char *r_error;
};
typedef struct r_val r_val;
#ifdef __cplusplus
extern "C" bool_t xdr_r_val(XDR *, r_val*);
#elif __STDC__
extern  bool_t xdr_r_val(XDR *, r_val*);
#else /* Old Style C */
bool_t xdr_r_val();
#endif /* Old Style C */


#define PHONE_BOOK_PROG ((rpc_uint)0x55550011)
#define PHONE_BOOK_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define ADD_TO_DATABASE ((rpc_uint)1)
extern "C" r_val * add_to_database_1(entry *, CLIENT *);
extern "C" r_val * add_to_database_1_svc(entry *, struct svc_req *);
#define REMOVE_FROM_DATABASE ((rpc_uint)2)
extern "C" r_val * remove_from_database_1(char **, CLIENT *);
extern "C" r_val * remove_from_database_1_svc(char **, struct svc_req *);
#define LOOKUP_NAME ((rpc_uint)3)
extern "C" r_val * lookup_name_1(char **, CLIENT *);
extern "C" r_val * lookup_name_1_svc(char **, struct svc_req *);
#define LIST ((rpc_uint)4)
extern "C" r_val * list_1(void *, CLIENT *);
extern "C" r_val * list_1_svc(void *, struct svc_req *);
#define QUIT ((rpc_uint)5)
extern "C" int * quit_1(void *, CLIENT *);
extern "C" int * quit_1_svc(void *, struct svc_req *);
#define TERMINATE ((rpc_uint)6)
extern "C" int * terminate_1(void *, CLIENT *);
extern "C" int * terminate_1_svc(void *, struct svc_req *);

#elif __STDC__
#define ADD_TO_DATABASE ((rpc_uint)1)
extern  r_val * add_to_database_1(entry *, CLIENT *);
extern  r_val * add_to_database_1_svc(entry *, struct svc_req *);
#define REMOVE_FROM_DATABASE ((rpc_uint)2)
extern  r_val * remove_from_database_1(char **, CLIENT *);
extern  r_val * remove_from_database_1_svc(char **, struct svc_req *);
#define LOOKUP_NAME ((rpc_uint)3)
extern  r_val * lookup_name_1(char **, CLIENT *);
extern  r_val * lookup_name_1_svc(char **, struct svc_req *);
#define LIST ((rpc_uint)4)
extern  r_val * list_1(void *, CLIENT *);
extern  r_val * list_1_svc(void *, struct svc_req *);
#define QUIT ((rpc_uint)5)
extern  int * quit_1(void *, CLIENT *);
extern  int * quit_1_svc(void *, struct svc_req *);
#define TERMINATE ((rpc_uint)6)
extern  int * terminate_1(void *, CLIENT *);
extern  int * terminate_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define ADD_TO_DATABASE ((rpc_uint)1)
extern  r_val * add_to_database_1();
extern  r_val * add_to_database_1_svc();
#define REMOVE_FROM_DATABASE ((rpc_uint)2)
extern  r_val * remove_from_database_1();
extern  r_val * remove_from_database_1_svc();
#define LOOKUP_NAME ((rpc_uint)3)
extern  r_val * lookup_name_1();
extern  r_val * lookup_name_1_svc();
#define LIST ((rpc_uint)4)
extern  r_val * list_1();
extern  r_val * list_1_svc();
#define QUIT ((rpc_uint)5)
extern  int * quit_1();
extern  int * quit_1_svc();
#define TERMINATE ((rpc_uint)6)
extern  int * terminate_1();
extern  int * terminate_1_svc();
#endif /* Old Style C */

#endif /* !_PHONE_BOOK_H_RPCGEN */
