/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include "phone_book.h"
#include "util.h"

r_val *
add_to_database_1_svc(entry *argp, struct svc_req *rqstp)
{
	static r_val  result;

	printf("args = %s and %s\n", argp->name, argp->number);

	// FILE *fp = fopen("database.txt", "a");

	// fprintf(fp, "%s# %s\n", argp->name, argp->number);

	result.r_num = 1;
	result.r_list = NULL;
	result.r_error = NULL;

	return(&result);
}

r_val *
remove_from_database_1_svc(char **argp, struct svc_req *rqstp)
{

	static r_val  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

r_val *
lookup_name_1_svc(char **argp, struct svc_req *rqstp)
{

	static r_val  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

r_val *
list_1_svc(void *argp, struct svc_req *rqstp)
{

	static r_val  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
quit_1_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
terminate_1_svc(void *argp, struct svc_req *rqstp)
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
