/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "phone_book.h"

r_val *
add_to_database_1_svc(entry *argp, struct svc_req *rqstp)
{
	static r_val  result;	

	entry e1;

	e1.name = (char*)malloc(sizeof(char) * 10);
	strcpy(e1.name, "david");

	e1.number = (char*)malloc(sizeof(char) * 10);
	strcpy(e1.number, "1234");

	e1.next = NULL;

	result.r_num = 0;
	result.r_list->head = &e1;
	result.r_error = NULL;

	return(&result);
}

r_val *
remove_from_database_1_svc(char **argp, struct svc_req *rqstp)
{
	static r_val  result;

	printf("in remove");

	return(&result);
}

r_val *
lookup_name_1_svc(char **argp, struct svc_req *rqstp)
{
	static r_val  result;

	printf("in lookup");

	return(&result);
}

r_val *
list_1_svc(void *argp, struct svc_req *rqstp)
{
	static r_val  result;

	printf("in list");

	return(&result);
}

int *
quit_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("in quit");

	return(&result);
}

int *
terminate_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("in terminate");

	return(&result);
}
